cartpole_key_control:
  ros__parameters:
    rate: 10.0
    scale: 10.0
    max_force: 256.0
    cart_path: "./src/cartpole/demonstrations/cart_1.txt"
    pole_path: "./src/cartpole/demonstrations/pole_1.txt"
