cartpole_key:
  ros__parameters:
    rate: 50.0
    scale: 0.01
    max_force: 10.0
    cart_path: "./src/cartpole/demonstrations/cart_1.txt"
    pole_path: "./src/cartpole/demonstrations/pole_1.txt"
